### ISSUE TITLE
kotlin.TypeCastException: null cannot be cast to non-null type replete.Item

### ISSUE THREAD

**Issue by mfikes** [replete-repl/replete-android#12]
Caught by the fuzz testing done by Google for build 5

```
1-19 13:16:17.597: I/Robo(12927): kotlin.TypeCastException: null cannot be cast to non-null type replete.Item
01-19 13:16:17.597: I/Robo(12927): 	at replete.MainActivity$onCreate$2$1.onActionItemClicked(Main.kt:408)
01-19 13:16:17.597: I/Robo(12927): 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2295)
01-19 13:16:17.597: I/Robo(12927): 	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:88)
01-19 13:16:17.597: I/Robo(12927): 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
01-19 13:16:17.597: I/Robo(12927): 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
01-19 13:16:17.597: I/Robo(12927): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
01-19 13:16:17.597: I/Robo(12927): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
01-19 13:16:17.597: I/Robo(12927): 	at com.android.internal.view.FloatingActionMode$4.onMenuItemClick(FloatingActionMode.java:114)
01-19 13:16:17.597: I/Robo(12927): 	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$3.onClick(FloatingToolbar.java:422)
01-19 13:16:17.597: I/Robo(12927): 	at android.view.View.performClick(View.java:5624)
01-19 13:16:17.597: I/Robo(12927): 	at android.view.View$PerformClick.run(View.java:22441)
01-19 13:16:17.597: I/Robo(12927): 	at android.os.Handler.handleCallback(Handler.java:751)
01-19 13:16:17.597: I/Robo(12927): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:164)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:156)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:34)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:75)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:50)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.action.Tap.c(Tap.java:8)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.action.Tap.a(Tap.java:18)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.action.Tap$1.b(Tap.java:3)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
01-19 13:16:17.597: I/Robo(12927): 	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
01-19 13:16:17.597: I/Robo(12927): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-19 13:16:17.597: I/Robo(12927): 	at android.os.Handler.handleCallback(Handler.java:751)
01-19 13:16:17.597: I/Robo(12927): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-19 13:16:17.597: I/Robo(12927): 	at android.os.Looper.loop(Looper.java:154)
01-19 13:16:17.597: I/Robo(12927): 	at android.app.ActivityThread.main(ActivityThread.java:6316)
01-19 13:16:17.597: I/Robo(12927): 	at java.lang.reflect.Method.invoke(Native Method)
01-19 13:16:17.597: I/Robo(12927): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
01-19 13:16:17.597: I/Robo(12927): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
01-19 13:16:17.597: I/Robo(12927): --------- beginning of crash
```

**Comment by roman01la** [comment]
Resolved in 98ac737
